---
- name: Manage ISOs
  ansible.builtin.import_tasks: manage_isos.yml
  when: storage_config.value.isos is defined

- name: Manage Container Templates
  ansible.builtin.import_tasks: manage_ct_templates.yml
  when: storage_config.value.ct_templates is defined
