apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: grafana/username
    - secretKey: password
      remoteRef:
        key: grafana/password
