apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  description: Cluster
  sourceRepos:
    - https://github.com/tillstuder/homelab.git
    - https://helm.cilium.io
    - https://charts.jetstack.io
    - https://charts.external-secrets.io
    - https://postfinance.github.io/kubelet-csr-approver
    - https://argoproj.github.io/argo-helm
    - docker.io/envoyproxy
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  description: Workloads
  sourceRepos:
    - https://github.com/tillstuder/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
