---
- name: Add distribution-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    cache_valid_time: "{{ common_unattended_cache_valid_time }}"
    update_cache: true
  become: true

- name: Create APT auto-upgrades configuration
  ansible.builtin.template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 5473
  become: true

- name: Create unattended-upgrades configuration
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 5473
  become: true

- name: Restart unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
    enabled: true
  become: true
