---
adguardhome_version: 0.107.52
adguardhome_user: adguardhome
adguardhome_group: adguardhome
adguardhome_daemon: adguardhome
adguardhome_home_dir: /var/lib/adguardhome
adguardhome_data_dir: "{{ adguardhome_home_dir }}"
adguardhome_bin_dir: /usr/local/bin
adguardhome_bin_file: "{{ adguardhome_bin_dir }}/AdGuardHome"
adguardhome_config_dir: /etc/adguardhome
adguardhome_config_file: "{{ adguardhome_config_dir }}/AdGuardHome.yaml"

adguardhome_manage_config: true

adguardhome_webhost: 0.0.0.0
adguardhome_webport: "80"
adguardhome_users:
  - username: "{{ lookup('ansible.builtin.env', 'ANSIBLE_ADGUARDHOME_USERNAME') }}"
    password: "{{ lookup('ansible.builtin.env', 'ANSIBLE_ADGUARDHOME_PASSWORD') }}"
adguardhome_auth_attempts: 5
adguardhome_block_auth_min: 15
adguardhome_http_proxy: '""'
adguardhome_language: en
adguardhome_web_session_ttl: 720h
adguardhome_dnshosts:
  - 0.0.0.0
adguardhome_dnsport: 53
adguardhome_statistics_enabled: "true"
adguardhome_statistics_interval: 720h
adguardhome_statistics_ignored: []
adguardhome_querylog_enabled: "true"
adguardhome_querylog_file_enabled: "true"
adguardhome_querylog_interval: 24h
adguardhome_querylog_size_memory: 1000
adguardhome_querylog_ignored: []
adguardhome_anonymize_client_ip: "false"
adguardhome_protection_enabled: "true"
adguardhome_blocking_mode: default
adguardhome_blockingipv4: '""'
adguardhome_blockingpiv6: '""'
adguardhome_blocked_response_ttl: 10
adguardhome_parental_block_host: family-block.dns.adguard.com
adguardhome_safebrowsing_block_host: standard-block.dns.adguard.com
adguardhome_ratelimit: 0
adguardhome_ratelimit_whitelist: []
adguardhome_refuse_any: "true"
adguardhome_upstream_dns:
  - tls://security.cloudflare-dns.com
adguardhome_upstream_dns_file: '""'
adguardhome_bootstrap_dns:
  - 1.1.1.1
  - 1.0.0.1
adguardhome_fastest_timeout: 1s
adguardhome_allowed_clients: []
adguardhome_disallowed_clients: []
adguardhome_blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
adguardhome_trusted_proxies:
  - 127.0.0.0/8
  - ::1/128
adguardhome_cache_size: 4194304
adguardhome_cache_ttl_min: 0
adguardhome_cache_ttl_max: 0
adguardhome_cache_optimistic: "false"
adguardhome_bogus_nxdomain: []
adguardhome_aaaa_disabled: "false"
adguardhome_enable_dnssec: "true"
adguardhome_edns_client_subnet: "false"
adguardhome_max_goroutines: 300
adguardhome_ipset: []
adguardhome_filtering_enabled: "true"
adguardhome_filters_update_interval: 1
adguardhome_parental_enabled: "false"
adguardhome_safesearch_enabled: "false"
adguardhome_safesearch:
  bing: "true"
  duckduckgo: "true"
  google: "true"
  pixabay: "true"
  yandex: "true"
  youtube: "true"
adguardhome_safebrowsing_enabled: "true"
adguardhome_safebrowsing_cache_size: 1048576
adguardhome_safeseach_cache_size: 1048576
adguardhome_parental_cache_size: 1048576
adguardhome_cache_time: 30
adguardhome_rewrites: []
adguardhome_blocked_services: [icloud_private_relay]
adguardhome_upstream_timeout: 10s
adguardhome_local_domain_name: lan
adguardhome_use_private_ptr_resolvers: "true"
adguardhome_local_ptr_upstreams: ["{{ lookup('ansible.builtin.env', 'NETWORK_SHORT') }}.1:53"]
adguardhome_tls_enabled: "false"
adguardhome_tls_server_name: '""'
adguardhome_tls_force_https: "false"
adguardhome_tls_port_https: 443
adguardhome_tls_port_dns_over_tls: 853
adguardhome_tls_port_dns_over_quic: 853
adguardhome_tls_port_dnscrypt: 0
adguardhome_tls_dnscrypt_config_file: '""'
adguardhome_tls_allow_enencrypted_doh: "false"
adguardhome_tls_sctrict_sni_check: "false"
adguardhome_tls_certificate_chain: '""'
adguardhome_tls_private_key: '""'
adguardhome_tls_certificate_path: '""'
adguardhome_tls_private_key_path: '""'
adguardhome_filters:
  - enabled: true
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
    name: HaGeZi's Pro DNS Blocklist
  - enabled: true
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/doh.txt
    name: HaGeZi's Encrypted DNS Bypass DNS Blocklist
  - enabled: true
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/spam-tlds.txt
    name: HaGeZi's The World's Most Abused TLDs
  - enabled: true
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.txt
    name: HaGeZi's Threat Intelligence Feeds DNS Blocklist
  - enabled: true
    url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
    name: Dandelion Sprout's Anti-Malware List
  - enabled: true
    url: https://raw.githubusercontent.com/xRuffKez/NRD/main/nrd-14day_adblock.txt
    name: xRuffKez's Newly Registered Domains
adguardhome_whitelist_filters:
  - enabled: true
    url: https://raw.githubusercontent.com/tillstuder/adguard_allowlist/main/list.txt
    name: Till Studer's Personal AdGuard Allowlist
adguardhome_user_rules: []
adguardhome_dhcp_enabled: "false"
adguardhome_dhcp_interface_name: '""'
adguardhome_dhcp_gateway_ip: '""'
adguardhome_dhcp_subnet_mask: '""'
adguardhome_dhcp_range_start: '""'
adguardhome_dhcp_range_end: '""'
adguardhome_dhcp_lease_duration: 86400
adguardhome_dhcp_icmp_timeout_msec: 1000
adguardhome_dhcp_options: []
adguardhome_dhcp6_range_start: '""'
adguardhome_dhcp6_lease_duration: 86400
adguardhome_dhcp6_slaac_only: "false"
adguardhome_dhcp6_allow_slaac: "false"
adguardhome_clients: []
adguardhome_runtime_sources_whois: "true"
adguardhome_runtime_sources_arp: "true"
adguardhome_runtime_sources_rdns: "{{ adguardhome_resolve_clients | default('true') }}"
adguardhome_runtime_sources_dhcp: "true"
adguardhome_runtime_sources_hosts: "true"
adguardhome_log_compress: "false"
adguardhome_log_localtime: "false"
adguardhome_log_max_backups: 0
adguardhome_log_max_size: 100
adguardhome_log_max_age: 3
adguardhome_log_enabled: "true"
adguardhome_log_file: '""'
adguardhome_verbose: "false"
adguardhome_os_group: '""'
adguardhome_os_user: '""'
adguardhome_rlimit_nofile: 0
adguardhome_private_networks: []
adguardhome_handle_ddr: "true"
adguardhome_ipset_file: '""'
adguardhome_serve_http3: "false"
adguardhome_use_http3_upstreams: "false"
adguardhome_theme: auto
adguardhome_use_dns64: "false"
adguardhome_dns64_prefixes: []
adguardhome_edns_client_subnet_custom_ip: '""'
adguardhome_edns_client_subnet_use_custom: "false"
adguardhome_protection_disabled_until: "null"
adguardhome_bootstrap_prefer_ipv6: "false"
adguardhome_blocked_services_time_zone: Local
adguardhome_pprof_port: 6060
adguardhome_pprof_enabled: "{{ adguardhome_debug_pprof | default('false') }}"
adguardhome_fallback_dns: [tls://dns.opendns.com]
adguardhome_ratelimit_subnet_len_ipv4: 24
adguardhome_ratelimit_subnet_len_ipv6: 56
adguardhome_serve_plain_dns: "true"
adguardhome_upstream_mode: load_balance
adguardhome_hostsfile_enabled: "true"
adguardhome_querylog_dir_path: '""'
adguardhome_statistics_dir_log: '""'
