---
all:
  vars:
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3

pve:
  hosts:
    pve1:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_IP_PVE1') }}"
      ansible_user: root
    pve2:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_IP_PVE2') }}"
      ansible_user: root

services:
  hosts:
    homer:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_IP_HOMER') }}"
      ansible_user: root
    adguardhome:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_IP_ADGUARDHOME') }}"
      ansible_user: root
    ntfy:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_IP_NTFY') }}"
      ansible_user: root
    gatus:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_IP_GATUS') }}"
      ansible_user: root
    tailscale:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_IP_TAILSCALE') }}"
      ansible_user: root
