apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/tillstuder/homelab.git
    targetRevision: main
    path: infrastructure/base/argo-cd/secret
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
