apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/tillstuder/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.21.1
      helm:
        releaseName: cert-manager
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/infrastructure/base/cert-manager/values.yaml
          - $values/clusters/dev/values/cert-manager.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: baseline
      pod-security.kubernetes.io/enforce-version: latest
      pod-security.kubernetes.io/warn: restricted
      pod-security.kubernetes.io/warn-version: latest
      pod-security.kubernetes.io/audit: restricted
      pod-security.kubernetes.io/audit-version: latest
