apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/tillstuder/homelab.git
      targetRevision: main
      ref: values
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.9.0
      helm:
        releaseName: envoy-gateway
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/infrastructure/base/envoy-gateway/values.yaml
          - $values/clusters/dev/values/envoy-gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/warn-version: latest
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: latest
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
