# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alloy-config.yaml
  - ./alloy.yaml
  - ./argo-cd-config.yaml
  - ./argo-cd.yaml
  - ./cert-manager-config.yaml
  - ./cert-manager.yaml
  - ./cilium-config.yaml
  - ./cilium.yaml
  - ./envoy-gateway-config.yaml
  - ./envoy-gateway.yaml
  - ./external-secrets-config.yaml
  - ./external-secrets.yaml
  - ./grafana-secret.yaml
  - ./grafana.yaml
  - ./kube-state-metrics.yaml
  - ./kubelet-csr-approver.yaml
  - ./local-path-provisioner.yaml
  - ./loki.yaml
  - ./network-policies.yaml
  - ./node-exporter.yaml
  - ./prometheus-operator-crds.yaml
  - ./prometheus.yaml
