apiVersion: cilium.io/v2
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lb-pool
spec:
  serviceSelector:
    matchExpressions:
      - key: io.kubernetes.service.namespace
        operator: In
        values:
          - envoy-gateway-system
  loadBalancerIPs: true
