# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
# talhelper genconfig --config-file talconfig-prod.yaml --env-file talenv.yaml
clusterName: prod
endpoint: https://10.42.5.200:6443

talosVersion: ${talosVersion}
kubernetesVersion: ${kubernetesVersion}

cniConfig:
  name: none

clusterPodNets: ["10.244.0.0/16"]
clusterSvcNets: ["10.96.0.0/12"]

allowSchedulingOnControlPlanes: true

nodes:
  - hostname: prod-cp-1
    ipAddress: 10.42.5.201
    controlPlane: true
    installDisk: /dev/sda                    # scsi0 on virtio-scsi-single
    networkInterfaces:
      - deviceSelector:
          driver: virtio_net                 # the VM's single net0 virtio NIC
        dhcp: false
        addresses: ["10.42.5.201/24"]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.42.5.1
        vip:
          ip: 10.42.5.200
  - hostname: prod-cp-2
    ipAddress: 10.42.5.202
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          driver: virtio_net                 # the VM's single net0 virtio NIC
        dhcp: false
        addresses: ["10.42.5.202/24"]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.42.5.1
        vip:
          ip: 10.42.5.200
  - hostname: prod-cp-3
    ipAddress: 10.42.5.203
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          driver: virtio_net                 # the VM's single net0 virtio NIC
        dhcp: false
        addresses: ["10.42.5.203/24"]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.42.5.1
        vip:
          ip: 10.42.5.200

patches:
  - "@./patches/kube-proxy-disabled.yaml"
  - "@./patches/cluster-discovery.yaml"
  - "@./patches/kubelet.yaml"
  - "@./patches/pod-security.yaml"
