apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: platform
  source:
    repoURL: https://github.com/tillstuder/homelab.git
    targetRevision: main
    path: infrastructure/prod/kube-system/cilium/config
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
