global:
  networkPolicy:
    create: false

configs:
  params:
    server.insecure: true
  repositories:
    envoy-gateway:
      name: envoy-gateway
      type: helm
      url: docker.io/envoyproxy
      enableOCI: "true"

controller:
  readinessProbe:
    timeoutSeconds: 5
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
server:
  podLabels:
    homelab.cyseclab.net/gateway-backend: "true" # Allows the Gateway to route traffic to this pod
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
repoServer:
  livenessProbe:
    timeoutSeconds: 5
  readinessProbe:
    timeoutSeconds: 5
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
