---
# Check for changes in config
- name: Check config file for changes.
  ansible.builtin.template:
    src: AdGuardHome.yaml.j2
    dest: "{{ adguardhome_config_file }}"
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_group }}"
    mode: "0644"
  check_mode: true

# Create AdGuard Home Service
- name: Create adguardhome systemd service file
  ansible.builtin.template:
    src: templates/{{ adguardhome_daemon }}.service.j2
    dest: /lib/systemd/system/{{ adguardhome_daemon }}.service
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_group }}"
    mode: "0644"

# Stop service as AdGuardHome overwrites changes when stopped
- name: Stop AdGuardHome.
  ansible.builtin.service:
    name: "{{ adguardhome_daemon }}"
    state: stopped

# Apply changes only if there are changes
- name: Copy config file.
  ansible.builtin.template:
    src: AdGuardHome.yaml.j2
    dest: "{{ adguardhome_config_file }}"
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_group }}"
    mode: "0644"
    backup: true

# Start AdGuardHome
- name: Start AdGuardHome.
  ansible.builtin.service:
    name: "{{ adguardhome_daemon }}"
    state: started
    enabled: true
