---
- name: Check if AdGuardHome is installed.
  ansible.builtin.stat:
    path: "{{ adguardhome_bin_file }}"

- name: Verify correct version of AdGuardHome has been installed.
  ansible.builtin.command: AdGuardHome --version
  args:
    chdir: /usr/local/bin
  changed_when: false
  register: __adguardhome_version
  failed_when: __adguardhome_version is not search(adguardhome_version)

- name: Check if adguardhome.service is started
  ansible.builtin.service:
    name: "{{ adguardhome_daemon }}"
    state: started
    enabled: true
  check_mode: true
  register: service
  until: service is succeeded
  retries: 3
  delay: 5
  failed_when: (service is changed) or (service is failed)
