---
- name: Install software dependencies
  ansible.builtin.package:
    name:
      - curl
    state: present

- name: Download the Go tarball
  ansible.builtin.get_url:
    url: https://golang.org/dl/{{ gatus_golang_tarball }}
    dest: /usr/local/src/{{ gatus_golang_tarball }}
    mode: "0644"

- name: Register the current Go version (if any)
  ansible.builtin.command: /usr/local/go/bin/go version
  ignore_errors: true
  register: go_version
  changed_when: false

- name: Remove old installation of Go
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  when: go_version is failed or go_version.stdout != gatus_golang_version_target

- name: Extract the Go tarball if Go is not yet installed or not the desired version
  ansible.builtin.unarchive:
    src: /usr/local/src/{{ gatus_golang_tarball }}
    dest: /usr/local
    copy: false
  when: go_version is failed or go_version.stdout != gatus_golang_version_target

- name: Add the Go bin directory to the PATH environment variable for all users
  ansible.builtin.copy:
    content: |
      export PATH=$PATH:/usr/local/go/bin
    dest: /etc/profile.d/golang.sh
    mode: "0644"
